image: node:14-slim
stages:
    # - build
    # - test
    - deploy

before_script:
  - node -v
  - npm i

cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"

# build_app:
#     stage: build
#     script:
#         - npm run build

# test_app:
#     stage: test
#     script:
#         - npm run test

pages:
    stage: deploy
    script:
        - npm run build && npm run export && mv out public
    artifacts:
        paths:
            - public
        # expire_in: 1h
    only:
        - feature/covid-data